[package]
name = "check-saved-receipts"
version = "0.1.0"
authors = ["Aleksandr Logunov <alex.logunov@near.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
serde_json = "1"
lazy_static = "1.4"
lazy-static-include = "3"

near-primitives = { path = "../../core/primitives" }
neard = {path = "../../neard"}
near-store = { path = "../../core/store" }
near-chain = { path = "../../chain/chain" }
near-jsonrpc = { path = "../../chain/jsonrpc" }

[features]
protocol_feature_restore_receipts_after_fix = []
nightly_protocol_features = ["nightly_protocol", "protocol_feature_restore_receipts_after_fix"]
nightly_protocol = []
